<?php if (array_key_exists('id', $_GET) && $_GET['id'] >= 1) : ?>
    <h2>Modification d'un produit</h2>
    <form action='index.php?controller=product&task=addOrUpdateProduct&id=<?= htmlspecialchars($_GET['id']) ?>' enctype="multipart/form-data" method='post'>
<?php else : ?>
    <h2>Ajout d'un produit</h2>
    <form action='index.php?controller=product&task=addOrUpdateProduct' enctype="multipart/form-data" method='post'>
<?php endif ?>

        <input type="hidden" name='token' value="<?= $_SESSION['user']['token'] ?>">

        <label for="name">Nom</label>
        <input class="admin" type="text" name='name' value="<?php echo array_key_exists('id', $_GET) ? htmlspecialchars($product['name']) : (array_key_exists('name', $_POST) ? htmlspecialchars($_POST['name']) : '') ?>" id="name">

        <label for="title">Appellation</label>
        <input class="admin" type="text" name='title' value="<?php echo array_key_exists('id', $_GET) ? htmlspecialchars($product['title']) : (array_key_exists('title', $_POST) ? htmlspecialchars($_POST['title']) : '') ?>" id="title">

        <label for="description">Description</label>
        <textarea class="admin" name='description' id="description"><?php echo array_key_exists('id', $_GET) ? htmlspecialchars($product['description']) : (array_key_exists('description', $_POST) ? htmlspecialchars($_POST['description']) : '') ?></textarea>

        <label for="stock">Stock</label>
        <input class="admin" type="number" name='stock' value="<?php echo array_key_exists('id', $_GET) ? htmlspecialchars($product['stock']) : (array_key_exists('stock', $_POST) ? htmlspecialchars($_POST['stock']) : '') ?>" id="stock">

        <label for="price">Prix</label>
        <input class="admin" type="text" name='price' value="<?php echo array_key_exists('id', $_GET) ? htmlspecialchars($product['price']) : (array_key_exists('price', $_POST) ? htmlspecialchars($_POST['price']) : '') ?>" id="price">

        <label for="grape">Cépage</label>
        <input class="admin" type="text" name='grape' value="<?php echo array_key_exists('id', $_GET) ? htmlspecialchars($product['grape']) : (array_key_exists('grape', $_POST) ? htmlspecialchars($_POST['grape']) : '') ?>" id="grape">

        <label for="country">Pays</label>
        <input class="admin" type="text" name='country' value="<?php echo array_key_exists('id', $_GET) ? htmlspecialchars($product['country']) : (array_key_exists('country', $_POST) ? htmlspecialchars($_POST['country']) : '') ?>" id="country">

        <label for="vintage">Millésime</label>
        <input class="admin" type="number" name='vintage' value="<?php echo array_key_exists('id', $_GET) ? htmlspecialchars($product['vintage']) : (array_key_exists('vintage', $_POST) ? htmlspecialchars($_POST['vintage']) : '') ?>" id="vintage">

        <label>Catégorie</label>
        <select class="admin" name="category">
            <option value="0">Catégorie</option>
            <?php for ($i = 0; $i < count($categories); $i++) : ?>
                <option value="<?= $i + 1 ?>" <?php if (array_key_exists('id', $_GET) && $_GET['id'] >= 1 && ($product['category']) === $categories[$i]['category']) : ?>selected<?php endif ?>>
                    <?= htmlspecialchars($categories[$i]['category']) ?>
                </option>
            <?php endfor ?>
        </select>

        <fieldset>
            <div class="field">
                <label for="file" class="form-label">Photo</label>
                <input type="hidden" name="MAX_FILE_SIZE" value="1048576">
                <input type="file" name="upload" id="file">
                <small>Choisir une image : Formats autorisés: 'jpg', 'gif', 'png'</small>
                <small>Taille maximale : 1Mo</small>
            </div>
        </fieldset>

        <?php if (array_key_exists('id', $_GET) && $_GET['id'] >= 1) : ?>
            <button class="button-admin" type='submit'>Je modifie le produit</button>
        <?php else : ?>
            <button class="button-admin" type='submit'>J'ajoute ce produit</button>
        <?php endif ?>

        <?php if (array_key_exists('id', $_GET) && $_GET['id'] >= 1) : ?>
            <div>
                <img src='<?= htmlspecialchars($product['picture']) ?>' class='product-img' alt="image de la bouteille">
            </div>
            <p>Image actuelle</p>
        <?php endif ?>
    </form>