<h1>Gestion des commandes</h1>
<table id="orders" class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Date de commande</th>
            <th>Utilisateur</th>
            <th>Statut</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($orders as $order) : ?>
            <tr>
                <td><?= $order['id'] ?></td>
                <td><?= $order['orderDate'] ?></td>
                <td><?= $order['firstname'], ' ', $order['lastname'] ?></td>
                <td><?= $order['status'] ?></td>
                <td class="actions"><a class="button-admin" href="#">Modifier</a><a class="button-admin delete" href="#">Supprimer</a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>