<h1>Gestion des contacts</h1>

<table id="contacts" class="table table-striped">
    <thead>
        <tr>
            <th>Sujet</th>
            <th>email</th>
            <th>contenu</th>
            <th>date</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($contacts as $contact) : ?>
            <tr>
                <td><?= $contact['subject'] ?></td>
                <td><?= $contact['email'] ?></td>
                <td><?= $contact['content'] ?></td>
                <td><?= $contact['created_at'] ?></td>
                <td class="actions">
                    <?php if ($contact['processed'] === 'off') : ?>
                        <a class="button-admin" href="index.php?controller=admin&task=processContact&id=<?= htmlspecialchars($contact['id']) ?>">Traité?</a>
                    <?php else : ?>
                        <a class="contact-processed button-admin" href="index.php?controller=admin&task=processContact&id=<?= htmlspecialchars($contact['id']) ?>">Traité</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>