<h1>Gestion des produits</h1>

<a class="button-admin add-product" href="index.php?controller=product&task=addProduct">Ajouter un produit</a>

<table id="products" class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Produit</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($products as $product) : ?>
            <tr>
                <td><?= $product['id'] ?></td>
                <td><?= $product['name'] ?></td>
                <td class="actions">
                    <a class="button-admin" href="index.php?controller=product&task=addProduct&id=<?= htmlspecialchars($product['id']) ?>">Modifier</a>
                    <?php if ($product['selected'] === 0) : ?>
                        <a class="button-admin" href="index.php?controller=admin&task=selectProduct&id=<?= htmlspecialchars($product['id']) ?>">Sélectionner</a>
                    <?php else : ?>
                        <a class="button-admin" href="index.php?controller=admin&task=selectProduct&id=<?= htmlspecialchars($product['id']) ?>">Désélectionner</a>
                        <?php endif; ?>
                    <form action="index.php?controller=admin&task=deleteProduct" method='POST'>
                        <input type="hidden" name='token' value="<?= $_SESSION['user']['token'] ?>">
                        <input type="hidden" name='product_id' value="<?= htmlspecialchars($product['id']) ?>">
                        <button class="button-admin delete" id="delete-button" onclick="return window.confirm(`Êtes vous sûr de vouloir bloquer ce produit ?!`)">Supprimer</button>
                    </form>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>