<h2>Mon panier</h2>
<?php if (isset($_COOKIE["shopping_cart"])) : ?>
    <table class="table cart">
        <thead>
            <th>Produit</th>
            <th>Nom</th>
            <th>Prix</th>
            <th>Quantité</th>
            <th>Total</th>
            <th>Action</th>
        </thead>
        <tbody>
            <?php $total = 0; $totalQuantity = 0;
            foreach ($cart_data as $keys => $values) : ?>
                <tr>
                    <td><img class='cart-img' src='<?= htmlspecialchars($values['item_picture']) ?>' /></td>
                    <td><?= htmlspecialchars($values['item_name']) ?></td>
                    <td><?= htmlspecialchars($values['item_price']) ?> €</td>
                    <td><?= htmlspecialchars($values['item_quantity']) ?></td>
                    <td><?= number_format($values["item_quantity"] * $values["item_price"], 2); ?> €</td>
                    <td><a href='index.php?controller=product&task=addToCart&id=<?= $values['item_id']; ?>' class='button delete'>Supprimer</td>
                </tr>
            <?php $total = $total + ($values["item_quantity"] * $values["item_price"]);
            $totalQuantity = $totalQuantity + $values["item_quantity"];
            setcookie('totalQuantity', $totalQuantity, time() + (86400 * 30));
            /* var_dump($totalQuantity);
            var_dump($_COOKIE); */
            endforeach ?>
        </tbody>
        <tfoot>
            <th colspan="5">Total <?= number_format($total, 2); ?>€</th>
            <th><a href='index.php?controller=product&task=addToCart&action=clear' class="button delete">Vider mon panier</a></th>
        </tfoot>
        
    </table>
    <a class="button" href='#'>Commander</a>

        <?php else : ?>
    <p>Votre panier est vide</p>
<?php endif ?>
