<h2>Modification de mot de passe</h2>

<form action='index.php?controller=user&task=changePassword' method='post'>

    <label for="currentPassword">Votre mot de passe actuel</label>
    <input class="front" type="password" name='currentPassword' id="currentPassword" required>

    <label for="newPassword">Votre nouveau mot de passe</label>
    <input class="front" type="password" name='newPassword' id="newPassword" required>
    <small>8 caractères minimum</small>

    <label for="newPasswordConfirm">Confirmez votre nouveau mot de passe</label>
    <input class="front" type="password" name='newPasswordConfirm' id="newPasswordConfirm" required>
    <small>8 caractères minimum</small>

    <input type="hidden" name='token' value="<?= $_SESSION['user']['token'] ?>">
    <button class="button">Je change mon mot de passe</button>
</form>