<h2>Modification de mot de passe</h2>

<form action='index.php?controller=user&task=changePassword' method='post'>
    <input type="hidden" name='token' value="<?= $_SESSION['user']['token'] ?>">
    <div class="field">
        <label for="currentPassword" class="form-label">Votre mot de passe actuel</label>
        <input type="password" name='currentPassword' id="currentPassword" required>
    </div>
    <div class="field">
        <label for="newPassword" class="form-label">Votre nouveau mot de passe</label>
        <input type="password" name='newPassword' id="newPassword" required>
    </div>
    <div class="field">
        <label for="newPasswordConfirm" class="form-label">Confirmez votre nouveau mot de passe</label>
        <input type="password" name='newPasswordConfirm' id="newPasswordConfirm" required>
    </div>
    <button class="button">Je change mon mot de passe</button>
</form>