<h1>Bienvenue sur Mon Petit Bouchon</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem quasi dolor porro minus reprehenderit neque delectus quos repudiandae sunt perferendis! Tenetur, esse ipsum asperiores pariatur ullam tempore quasi fuga dolor vitae aut animi possimus modi iusto ad unde inventore eos totam soluta itaque laudantium porro! Natus maxime consequatur, ad quas quae illo laboriosam. Delectus minima odit perferendis eum saepe hic aperiam voluptates quos consectetur, vitae quod asperiores soluta animi! Quod atque ex deserunt dolorem vel nisi eaque, quibusdam quis, mollitia eveniet quos assumenda error! Vero ratione esse a enim. Ipsa dignissimos quasi ipsum veritatis distinctio saepe suscipit a tempora voluptas!</p>
<div class="products">
    <?php foreach ($products as $product) : ?>
        <div>
            <img src='<?= htmlspecialchars($product['picture']) ?>' style='width:100px' />
        </div>
        <div>
            <h2><?= htmlspecialchars($product['name']) ?></h2>
            <h3><?= htmlspecialchars($product['title']) ?></h3>
            <p><?= htmlspecialchars($product['price']) ?> €</p>
            <a class="button" href="index.php?controller=product&task=showOne&id=<?= htmlspecialchars($product['id']) ?>">Plus d'informations</a>
        </div>
    <?php endforeach; ?>
</div>