<h1>Bienvenue sur Mon Petit Bouchon</h1>
<p>Bienvenue sur notre dédié au vin !</p>

<p>Découvrez un monde de saveurs et d'élégance au bout de vos doigts. Que vous soyez un amateur passionné ou un connaisseur expérimenté, notre sélection minutieuse de vins vous promet une expérience gustative inoubliable.</p>

<p>Plongez dans notre cave virtuelle et laissez-vous séduire par notre vaste gamme de vins provenant des quatre coins de France. Des rouges intenses aux blancs rafraîchissants, en passant par les rosés délicats, nous avons soigneusement choisi chaque bouteille pour vous offrir le meilleur de chaque terroir.</p>

<p>Nous collaborons directement avec des producteurs renommés et des domaines familiaux, afin de vous garantir des vins d'une qualité exceptionnelle. Chaque bouteille est le fruit d'un savoir-faire ancestral et d'une passion pour le vin, transmise de génération en génération.</p>

<p>Naviguez à travers nos catégories et laissez-vous guider par nos descriptions détaillées, les avis des consommateurs et les notes de dégustation. Que vous recherchiez un vin pour une occasion spéciale, une bouteille à offrir en cadeau ou simplement un nouveau cépage à explorer, nous avons tout ce qu'il vous faut.</p>

<p>La satisfaction de nos clients est notre priorité absolue. Notre équipe dévouée est là pour répondre à toutes vos questions et vous assister dans votre processus d'achat. Nous vous proposons également une livraison rapide et sécurisée, directement à votre porte, pour que vous puissiez profiter de vos précieuses découvertes sans attendre.</p>

<p>Rejoignez-nous dans notre passion pour le vin et laissez-nous vous accompagner dans l'exploration de nouvelles sensations gustatives. Parcourez notre site dès maintenant et laissez les arômes envoûtants vous transporter dans un voyage vinique exceptionnel.</p>

<p>Bienvenue dans notre univers vinicole. Santé !</p>
<article>
    <h2>Déguster un vin :</h2>
    <video poster="./public/img/poster_logo.jpg" controls>
        Votre navigateur est obsolète. Pour pouvoir lire cette vidéo, veuillez le mettre à jour.
        <source src="./public/video/videoplayback.mp4" type="video/mp4">
        <!-- <source src="medias/bunny.ogv" type="video/ogv"> -->
    </video>
</article>
<h2>À ne pas rater en ce moment :</h2>
<div class="products">
    <?php foreach ($products as $product) : ?>
        <div>
            <img src='<?= htmlspecialchars($product['picture']) ?>' style='width:100px' />
        </div>
        <div>
            <h2><?= htmlspecialchars($product['name']) ?></h2>
            <h3><?= htmlspecialchars($product['title']) ?></h3>
            <p><?= htmlspecialchars($product['price']) ?> €</p>
            <a class="button" href="index.php?controller=product&task=showOne&id=<?= htmlspecialchars($product['id']) ?>">Plus d'informations</a>
        </div>
    <?php endforeach; ?>
</div>