<h2>Connexion</h2>

<form action='index.php?controller=user&task=login' method='post'>
    <!-- <div class="field"> -->
        <label for="mail">Votre email</label>
        <input class="front" type="email" name='mail' id="mail">
    <!-- </div>
    <div class="field"> -->
        <label for="password">Votre mot de passe</label>
        <input class="front" type="password" name='password' id="password" required>
    <!-- </div>
    <div> -->
        <button class="button">Je me connecte</button>
    <!-- </div> -->
</form>