<h2>Connexion</h2>

<form action='index.php?controller=user&task=login' method='post'>
    <!-- <div class="field"> -->
        <label for="mail" class="form-label">Votre email</label>
        <input type="email" name='mail' class="form-control" id="mail" aria-describedby="emailHelp">
    <!-- </div>
    <div class="field"> -->
        <label for="password" class="form-label">Votre mot de passe</label>
        <input type="password" name='password' class="form-control" id="password" required>
    <!-- </div>
    <div> -->
        <button class="button">Je me connecte</button>
    <!-- </div> -->
</form>