<h2>Mon Compte</h2>

<div class="box">
    <h3>Bienvenue <?= htmlspecialchars($user['firstname']) ?> !</h3>
    <p>Retrouvez ici toutes vos informations personnelles et l'historique de vos commandes</p>
</div>
<div>
    <h3>Mes données personnelles</h3>
    <div class="box">
        <h4><?= $user['firstname']; ?> <?= $user['lastname']; ?></h4>
        <p><?= $user['address']; ?></p>
        <p><?= $user['zipCode']; ?></p>
        <p><?= $user['city']; ?></p>
        <p><?= $user['country']; ?></p>
    </div>
</div>
<a class="button" href="index.php?controller=user&task=changePassword">Modifier mon mot de passe</a> 
<a class="button" href="index.php?controller=user&task=myOrders">Mes commandes</a>