<h2>Mon Compte</h2>

<div class="box">
    <h3>Bienvenue <?= htmlspecialchars($user['firstname']) ?> !</h3>
    <p>Retrouvez ici toutes vos informations personnelles et l'historique de vos commandes</p>
</div>
<div>
    <h3>Mes données personnelles</h3>
    <div class="box">
        <h4><?= htmlspecialchars($user['firstname']); ?> <?= htmlspecialchars($user['lastname']); ?></h4>
        <p><?= htmlspecialchars($user['address']); ?></p>
        <p><?= htmlspecialchars($user['zipCode']); ?></p>
        <p><?= htmlspecialchars($user['city']); ?></p>
        <p><?= htmlspecialchars($user['country']); ?></p>
    </div>
</div>
<a class="button" href="index.php?controller=user&task=changePassword">Modifier mon mot de passe</a> 
<a class="button" href="index.php?controller=product&task=showOrders">Mes commandes</a>