<h1 id="mentions1">Mentions légales et conditions générales de vente</h1>
<div class="mentions">
    <div >
        <a href="#mentions" >Mentions légales</a>
        <a href="#mentions1">1. Informations sur Mon Petit Bouchon</a>
        <a href="#mentions2">2. Données peronnelles</a>
        <a href="#mentions3">3. Modifications</a>
    </div>
    <h2 id="mentions">
        Mentions légales</h2>
    <p>Conformément à l'article L.3342-1 du Code de la santé publique et à la loi n°2009-879
        du 21 juillet 2009, la vente d'alcool à des mineurs est
        interdite.</br>Il est déconseillé aux femmes enceintes de consommer de
        l’alcool, même à faible dose.</br><strong>L’ABUS D’ALCOOL EST DANGEREUX POUR LA
            SANTE. A CONSOMMER AVEC MODERATION.</strong> </br>Conformément aux dispositions de
        l'article 6 III-1 de la loi n°2004-575 du 21 juin 2004 pour la confiance dans l'économie
        numérique, nous vous informons que le présent site <a href="https://www.lepetitballon.com">https://www.lepetitballon.com</a> (ci-après le «
        <strong>Site</strong> ») est la propriété exclusive de la société Mon Petit Bouchon.
    </p>
    <ol>
        <h2 id="mentions1">1.
            Informations sur Mon Petit Bouchon</h2>
    </ol>
    <p>Mon Petit Bouchon est société par action simplifiée au capital social de 79.910 euros,
        immatriculée au Registre du Commerce et des Sociétés de Paris sous le numéro B 42 42 42,
        dont le numéro de TVA intracommunautaire est FR42424242 et dont le siège social se situe
        42 rue du rocher, 42000 Saint Etienne (ci-après désignée la « <strong>Société</strong> »).</br>Les
        coordonnées de la Société sont les suivantes :</br><strong>Mon Petit Bouchon</strong></br>42,
        rue du Rocher
    <p>42000 Saint Etienne
    <p>Email : <a href="/cdn-cgi/l/email-protection#ea88858480859f98aa868f9a8f9e839e888b86868584c4898587"><strong><span class="__cf_email__" data-cfemail="80e2efeeeaeff5f2c0ece5f0e5f4e9f4e2e1ececefeeaee3efed">[email&#160;protected]</span></strong></a>
        </br>Le directeur de publication est Monsieur Martin Ohannessian, Président de la
        Société. </br>Le Site est hébergé par la société Amazon CS Ireland Ltd. Amazon CS
        Ireland Ltd est une société du groupe Amazon Web Services (AWS), dont le siège
        social se situe à Inc. P.O/ Box 81226 - Seattle, WA 98108-1226, tél : (206) 266-4064
        (<a href="https://aws.amazon.com">https://aws.amazon.com</a>). </p>
    <ol start="2">
        <h2 id="mentions2" class="MagentoCms-cms__subtitle--large" style="text-align: left;">2. Données personnelles</h2>
    </ol>
    <p>La Société peut être amenée à collecter des données personnelles concernant
        l’utilisateur du Site.</br>Pour plus d’informations concernant le traitement des
        données personnelles, l’utilisateur est invité à consulter la Charte Vie Privée,
        accessible via à l’adresse suivante <a href="https://www.lepetitballon.com/vieprivee">https://www.lepetitballon.com/vieprivee</a>.
    </p>
    <ol start="3">
        <h2 id="mentions3">3. Modifications</h2>
    </ol>
    <p>Mon Petit Bouchon se réserve la possibilité de modifier ou de compléter les présentes
        mentions légales à tout moment et sans préavis. L’utilisateur est tenu de consulter
        régulièrement les présentes mentions légales.</p>
</div>