<h1>Nos vins</h1>

<!-- Searchbar -->
<form class="field">
    <input class="front" type="text" name="search" id="search" placeholder="Rechercher un vin, une appellation, un millésime...">
</form>

<!-- div in which we will display the result of our search -->
<div class="result" id="result"></div>
<h2>Tous nos produits ci dessous :</h2>
<div class="products-index">
    <?php foreach ($products as $product) : ?>
        <div class="products">
            <div>
                <img src='<?= htmlspecialchars($product['picture']) ?>' class='product-img' alt='image de la bouteille'>
            </div>
            <div>
                <h2><?= htmlspecialchars($product['name']) ?></h2>
                <h3><?= htmlspecialchars($product['title']) ?></h3>
                <p><?= htmlspecialchars($product['price']) ?> €</p>
                <a class="button" href="index.php?controller=product&task=showOne&id=<?= htmlspecialchars($product['id']) ?>">Plus d'informations</a>
            </div>
        </div>
    <?php endforeach; ?>
</div>