<h2>Fiche produit</h2>

<img src='<?= htmlspecialchars($product['picture']) ?>' class='product-img'/>
<h2><?= htmlspecialchars($product['name']) ?></h2>
<h3><?= htmlspecialchars($product['title']) ?></h3>
<h4><?= htmlspecialchars($product['category']) ?></h4>
<p><?= nl2br(htmlspecialchars($product['description'])) ?></p>
<p><?= htmlspecialchars($product['price']) ?> €</p>
<?php if($product['stock'] > 0) : ?>
    <h3>Stock: <?= htmlspecialchars($product['stock']) ?></h3>
<?php else : ?>
    <h3>Victime de son succès</h3>
<?php endif; ?>

<form action="index.php?controller=product&task=addToCart&id=<?= htmlspecialchars($product['id']) ?>" method='POST'>
    <!-- <input type="hidden" name="hidden_picture" value="<?= htmlspecialchars($product['picture']) ?>" />
    <input type="hidden" name="hidden_name" value="<?= htmlspecialchars($product['name']) ?>" />
    <input type="hidden" name="hidden_price" value="<?= htmlspecialchars($product['price']) ?>" />
    <input type="hidden" name='hidden_id' value="<?= htmlspecialchars($product['id']) ?>"> -->
    <input type="text" name="quantity" id="quantity" value="1" />
    <button class="button" type="submit" name="add_to_cart" id="button" value='Add to Cart'>Ajouter au panier</button>
</form>
<!-- <a class="button" href="index.php?controller=product&task=addToCart&id=<?= htmlspecialchars($product['id']) ?>">Ajouter au panier</a> -->

<div class="opinions">
    <h3>L'avis des utilisateurs</h3>
    <?php if (!empty($opinions)) : ?>
        <div class="opinions">
            <?php foreach ($opinions as $opinion) : ?>
                <p>Note <?= htmlspecialchars($opinion['score']) ?>/5</p>
                <h4><?= htmlspecialchars($opinion['title']) ?></h4>
                <p><?= htmlspecialchars($opinion['opinion']) ?></p>
                <p><?= htmlspecialchars($opinion['pseudo']), ', le ', htmlspecialchars($opinion['created_at']) ?></p>
            <?php endforeach; ?>
        </div>
    <?php else : ?>
        <p>Il n'y a pas encore d'avis pour ce produit</p>
    <?php endif; ?>
</div>

<div class="box opinion">
    <h3>Votre avis nous intéresse</h3>
    <?php if (isset($_SESSION['user'])) : ?>
        <form action='index.php?controller=user&task=opinion&id=<?= htmlspecialchars($product['id']) ?>' method='post'>
            <div class="rating">
                <div class="stars">
                <svg class='img-star' viewBox="0 0 576 512"><path d="M316.9 18C311.6 7 300.4 0 288.1 0s-23.4 7-28.8 18L195 150.3 51.4 171.5c-12 1.8-22 10.2-25.7 21.7s-.7 24.2 7.9 32.7L137.8 329 113.2 474.7c-2 12 3 24.2 12.9 31.3s23 8 33.8 2.3l128.3-68.5 128.3 68.5c10.8 5.7 23.9 4.9 33.8-2.3s14.9-19.3 12.9-31.3L438.5 329 542.7 225.9c8.6-8.5 11.7-21.2 7.9-32.7s-13.7-19.9-25.7-21.7L381.2 150.3 316.9 18z"/></svg>
                <svg class='img-star' viewBox="0 0 576 512"><path d="M287.9 0c9.2 0 17.6 5.2 21.6 13.5l68.6 141.3 153.2 22.6c9 1.3 16.5 7.6 19.3 16.3s.5 18.1-5.9 24.5L433.6 328.4l26.2 155.6c1.5 9-2.2 18.1-9.6 23.5s-17.3 6-25.3 1.7l-137-73.2L151 509.1c-8.1 4.3-17.9 3.7-25.3-1.7s-11.2-14.5-9.7-23.5l26.2-155.6L31.1 218.2c-6.5-6.4-8.7-15.9-5.9-24.5s10.3-14.9 19.3-16.3l153.2-22.6L266.3 13.5C270.4 5.2 278.7 0 287.9 0zm0 79L235.4 187.2c-3.5 7.1-10.2 12.1-18.1 13.3L99 217.9 184.9 303c5.5 5.5 8.1 13.3 6.8 21L171.4 443.7l105.2-56.2c7.1-3.8 15.6-3.8 22.6 0l105.2 56.2L384.2 324.1c-1.3-7.7 1.2-15.5 6.8-21l85.9-85.1L358.6 200.5c-7.8-1.2-14.6-6.1-18.1-13.3L287.9 79z"/></svg>
                <svg class='img-star' viewBox="0 0 576 512"><path d="M287.9 0c9.2 0 17.6 5.2 21.6 13.5l68.6 141.3 153.2 22.6c9 1.3 16.5 7.6 19.3 16.3s.5 18.1-5.9 24.5L433.6 328.4l26.2 155.6c1.5 9-2.2 18.1-9.6 23.5s-17.3 6-25.3 1.7l-137-73.2L151 509.1c-8.1 4.3-17.9 3.7-25.3-1.7s-11.2-14.5-9.7-23.5l26.2-155.6L31.1 218.2c-6.5-6.4-8.7-15.9-5.9-24.5s10.3-14.9 19.3-16.3l153.2-22.6L266.3 13.5C270.4 5.2 278.7 0 287.9 0zm0 79L235.4 187.2c-3.5 7.1-10.2 12.1-18.1 13.3L99 217.9 184.9 303c5.5 5.5 8.1 13.3 6.8 21L171.4 443.7l105.2-56.2c7.1-3.8 15.6-3.8 22.6 0l105.2 56.2L384.2 324.1c-1.3-7.7 1.2-15.5 6.8-21l85.9-85.1L358.6 200.5c-7.8-1.2-14.6-6.1-18.1-13.3L287.9 79z"/></svg>
                <svg class='img-star' viewBox="0 0 576 512"><path d="M287.9 0c9.2 0 17.6 5.2 21.6 13.5l68.6 141.3 153.2 22.6c9 1.3 16.5 7.6 19.3 16.3s.5 18.1-5.9 24.5L433.6 328.4l26.2 155.6c1.5 9-2.2 18.1-9.6 23.5s-17.3 6-25.3 1.7l-137-73.2L151 509.1c-8.1 4.3-17.9 3.7-25.3-1.7s-11.2-14.5-9.7-23.5l26.2-155.6L31.1 218.2c-6.5-6.4-8.7-15.9-5.9-24.5s10.3-14.9 19.3-16.3l153.2-22.6L266.3 13.5C270.4 5.2 278.7 0 287.9 0zm0 79L235.4 187.2c-3.5 7.1-10.2 12.1-18.1 13.3L99 217.9 184.9 303c5.5 5.5 8.1 13.3 6.8 21L171.4 443.7l105.2-56.2c7.1-3.8 15.6-3.8 22.6 0l105.2 56.2L384.2 324.1c-1.3-7.7 1.2-15.5 6.8-21l85.9-85.1L358.6 200.5c-7.8-1.2-14.6-6.1-18.1-13.3L287.9 79z"/></svg>
                <svg class='img-star' viewBox="0 0 576 512"><path d="M287.9 0c9.2 0 17.6 5.2 21.6 13.5l68.6 141.3 153.2 22.6c9 1.3 16.5 7.6 19.3 16.3s.5 18.1-5.9 24.5L433.6 328.4l26.2 155.6c1.5 9-2.2 18.1-9.6 23.5s-17.3 6-25.3 1.7l-137-73.2L151 509.1c-8.1 4.3-17.9 3.7-25.3-1.7s-11.2-14.5-9.7-23.5l26.2-155.6L31.1 218.2c-6.5-6.4-8.7-15.9-5.9-24.5s10.3-14.9 19.3-16.3l153.2-22.6L266.3 13.5C270.4 5.2 278.7 0 287.9 0zm0 79L235.4 187.2c-3.5 7.1-10.2 12.1-18.1 13.3L99 217.9 184.9 303c5.5 5.5 8.1 13.3 6.8 21L171.4 443.7l105.2-56.2c7.1-3.8 15.6-3.8 22.6 0l105.2 56.2L384.2 324.1c-1.3-7.7 1.2-15.5 6.8-21l85.9-85.1L358.6 200.5c-7.8-1.2-14.6-6.1-18.1-13.3L287.9 79z"/></svg>
                </div>
            </div> 
            
            
            <div class="field">
                <input type="radio" id="parfait" name="score" value=5>
                <label for="parfait">Parfait</label><br>
                <input type="radio" id="tbon" name="score" value=4>
                <label for="tbon">Très bon</label><br>
                <input type="radio" id="bon" name="score" value=3>
                <label for="bon">Bon</label>
                <input type="radio" id="moyen" name="score" value=2>
                <label for="moyen">Moyen</label>
                <input type="radio" id="mauvais" name="score" value=1>
                <label for="mauvais">Mauvais</label>
            </div>
            <div class="field">
                <label for="pseudo">Votre pseudo</label>
                <input type="text" name='pseudo' value="<?php if(!empty($_POST['pseudo'])) echo $_POST['pseudo']; ?>" id="pseudo" aria-describedby="emailHelp">
            </div>
            <div class="field">
                <label for="title">Votre avis en 2 mots</label>
                <input type="text" name='title' value="<?php if(!empty($_POST['title'])) echo $_POST['title']; ?>" id="title" aria-describedby="emailHelp">
            </div>
            <div class="field">
                <label for="opinion">Votre avis</label>
                <textarea name='opinion' id="opinion" required><?php if(!empty($_POST['opinion'])) echo $_POST['opinion']; ?></textarea>
            </div>
            <input type="hidden" name="product_id" value="<?= $product['id'] ?>">
            <button class="button">Je partage mon avis</button>
        </form>
    <?php else : ?>
        <h4>On a hâte de vous lire !</h4>
        <p>Connectez-vous ou créez un compte pour partager votre avis avec la Grande Famille du Petit Bouchon.</p>
        <a class='button' href='index.php?controller=user&task=login'>Se connecter</a>
        <a class='button' href='index.php?controller=user&task=register'>Créer un compte</a>
    <?php endif; ?>
</div>