<h2>Fiche produit</h2>

<img src='<?= htmlspecialchars($product['picture']) ?>' class='product-img' alt='image de la bouteille'>
<h2><?= htmlspecialchars($product['name']) ?></h2>
<h3><?= htmlspecialchars($product['title']) ?></h3>
<h4><?= htmlspecialchars($product['category']) ?></h4>
<p><?= nl2br(htmlspecialchars($product['description'])) ?></p>
<p><?= htmlspecialchars($product['price']) ?> €</p>
<?php if ($product['stock'] > 0) : ?>
    <h3>Stock: <?= htmlspecialchars($product['stock']) ?></h3>
<?php else : ?>
    <h3>Victime de son succès</h3>
<?php endif; ?>

<form action="index.php?controller=product&task=addToCart&id=<?= htmlspecialchars($product['id']) ?>" method='POST'>
    <label for="quantity">Quantité</label>
    <input class="front" type="text" name="quantity" id="quantity" value="1">
    <button class="button" type="submit" name="add_to_cart" id="button" value='Add to Cart'>Ajouter au panier</button>
</form>

<div class="opinions">
    <h3>L'avis des utilisateurs</h3>
    <?php if (!empty($opinions)) : ?>
        <div class="opinions">
            <?php foreach ($opinions as $opinion) : ?>
                <p>Note <?= htmlspecialchars($opinion['score']) ?>/5</p>
                <h4><?= htmlspecialchars($opinion['title']) ?></h4>
                <p><?= htmlspecialchars($opinion['opinion']) ?></p>
                <p class="opinion"><?= htmlspecialchars($opinion['pseudo']), ', le ', htmlspecialchars($opinion['created_at']) ?></p>
            <?php endforeach; ?>
        </div>
    <?php else : ?>
        <p>Il n'y a pas encore d'avis pour ce produit</p>
    <?php endif; ?>
</div>

<div class="box opinion">
    <h3>Votre avis nous intéresse</h3>
    <?php if (isset($_SESSION['user'])) : ?>
        <form action='index.php?controller=user&task=opinion&id=<?= htmlspecialchars($product['id']) ?>' method='post'>
            <input type="hidden" name='token' value="<?= $_SESSION['user']['token'] ?>">
            <label>Note</label>
            <select class="front" name="score">
                <option value=5>Excellent 5/5</option>
                <option value=4>Très bon 4/5</option>
                <option value=3>Correct 3/5</option>
                <option value=2>Passable 2/5</option>
                <option value=1>Mauvais 1/5</option>
            </select>

                <label for="pseudo">Votre pseudo</label>
                <input class="front" type="text" name='pseudo' value="<?php if (!empty($_POST['pseudo'])) echo $_POST['pseudo']; ?>" id="pseudo">

                <label for="title">Votre avis en 2 mots</label>
                <input class="front" type="text" name='title' value="<?php if (!empty($_POST['title'])) echo $_POST['title']; ?>" id="title">

                <label for="opinion">Votre avis</label>
                <textarea class="front" name='opinion' id="opinion" required><?php if (!empty($_POST['opinion'])) echo $_POST['opinion']; ?></textarea>

            <input type="hidden" name="product_id" value="<?= $product['id'] ?>">
            <button class="button" type="submit">Je partage mon avis</button>
        </form>
    <?php else : ?>
        <h4>On a hâte de vous lire !</h4>
        <p>Connectez-vous ou créez un compte pour partager votre avis avec la Grande Famille du Petit Bouchon.</p>
        <a class='button' href='index.php?controller=user&task=login'>Se connecter</a>
        <a class='button' href='index.php?controller=user&task=register'>Créer un compte</a>
    <?php endif; ?>
</div>