<h2>Inscription</h2>

<form action='index.php?controller=user&task=register' method='post'>
    <!-- <div class="field"> -->
        <label for="mail">Votre mail</label>
        <input class="front" type="email" name='mail' value="<?php if(!empty($_POST['mail'])) echo $_POST['mail']; ?>" id="mail" aria-describedby="emailHelp">
    <!-- </div> -->
    <!-- <div class="field"> -->
        <label for="firstname">Votre prénom</label>
        <input class="front" type="text" name='firstname' value="<?php if(!empty($_POST['firstname'])) echo $_POST['firstname']; ?>" id="firstname" aria-describedby="emailHelp">
    <!-- </div>
    <div class="field"> -->
        <label for="lastname" class="form-label">Votre nom</label>
        <input class="front" type="text" name='lastname' value="<?php if(!empty($_POST['lastname'])) echo $_POST['lastname']; ?>" id="lastname" aria-describedby="emailHelp">
    <!-- </div> -->
    <!-- <div class="field"> -->
        <label for="birthday" class="form-label">Votre date de naissance</label>
        <input class="front" type="date" name='birthday' value="<?php if(!empty($_POST['birthday'])) echo $_POST['birthday']; ?>"id="birthday" aria-describedby="emailHelp">
    <!-- </div>
    <div class="field"> -->
        <label for="address" class="form-label">Votre adresse</label>
        <input class="front" type="text" name='address' value="<?php if(!empty($_POST['address'])) echo $_POST['address']; ?> "id="address" aria-describedby="emailHelp">
    <!-- </div>
    <div class="field"> -->
        <label for="zipCode" class="form-label">Votre code postal</label>
        <input class="front" type="text" name='zipCode' value="<?php if(!empty($_POST['zipCode'])) echo $_POST['zipCode']; ?>"id="zipCode" aria-describedby="emailHelp">
    <!-- </div>
    <div class="field"> -->
        <label for="city" class="form-label">Votre ville</label>
        <input class="front" type="text" name='city' value="<?php if(!empty($_POST['city'])) echo $_POST['city']; ?>" id="city" aria-describedby="emailHelp">
    <!-- </div>
    <div class="field"> -->
        <label for="country" class="form-label">Votre pays</label>
        <input class="front" type="text" name='country' value="<?php if(!empty($_POST['country'])) echo $_POST['country']; ?>" id="country" aria-describedby="emailHelp">
    <!-- </div>
    <div class="field"> -->
        <label for="password" class="form-label">Votre mot de passe</label>
        <input class="front" type="password" name='password' value="<?php if(!empty($_POST['password'])) echo $_POST['password']; ?>" id="password" required>
        <small>8 caractères minimum</small>
    <!-- </div> -->
    <button type="submit" class="button">Je créé mon compte</button>
</form>