<h1>Mise à jour commande <?= htmlspecialchars($order['id']) ?></h1>

<form action='index.php?controller=product&task=updateOrder&id=<?= htmlspecialchars($order['id']) ?>' method='post'>
    <input type="hidden" name='token' value="<?= $_SESSION['user']['token'] ?>">
    <label>Statut</label>
    <select name="status">
        <option value="Commande confirmée">Commande confirmée</option>
        <option value="Commande en préparation">Commande en préparation</option>
        <option value="Commande expédiée">Commande expédiée</option>
        <option value="Commande livrée">Commande livrée</option>
    </select>
    <button class="button-admin" type='submit'>Je modifie le statut</button>
</form>